apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  names:
    kind: MyCustomResource
    plural: mycustomresources
    singular: mycustomresource
    shortNames:
      - mcr
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validation:
                - rule: "self['xyz'].foo > 0"
                  message: "foo property must be greater than 0"
              additionalProperties:
                xyz:
                  type: object
                  properties:
                    foo:
                      type: integer