apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  names:
    kind: MyCustomResource
    plural: mycustomresources
    singular: mycustomresource
    shortNames:
      - mcr
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            foo:
              type: array
              x-kubernetes-validation:
                - rule: "size(self) == 1"
                  message: "size of foo must be 1"
              items:
                type: string