apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  names:
    kind: MyCustomResource
    plural: mycustomresources
    singular: mycustomresource
    shortNames:
      - mcr
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validation:
                - rule: "self.replicas <= self.maxReplicas"
                  message: "replicas must be less than or equal to maxReplicas"
              properties:
                replicas:
                  type: integer
                maxReplicas:
                  type: integer
              required:
                - replicas
                - maxReplicas